apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: ggckad
spec:
  containers:
    - name: alpine-spin
      image: kubegoldenguide/alpine-spin:1.0.0
    - name: nginx
      image: nginx:1.7.9