apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-5-deployment
  labels:
    client: user
spec:
  replicas: 6
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: revproxy
  template:
    metadata:
      name: question-5-pod
      labels:
        app: revproxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9