apiVersion: v1
kind: Pod
metadata:
  name: question-two-pod
  labels:
    app: ggckad
spec:
  containers:
    - name: alpine-spin
      image: kubegoldenguide/alpine-spin:1.0.0
      envFrom:
        - configMapRef:
            name: app-config